name: Daily Lesson with Images

on:
  schedule:
    - cron: '0 22 * * *'  # 每日 06:00 台北時間 (UTC+8)
  workflow_dispatch:

jobs:
  generate-lessons:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Generate lessons with images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python main_with_images.py
    
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git commit -m "Daily lesson update with images: $(date +'%Y-%m-%d')" || exit 0
        git push